"""
Chat model module defining the database schema for chat interactions.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime
from src.database.config import Base

class Chat(Base):
    """
    Chat model representing a conversation entry.
    
    Attributes:
        id: Unique identifier for the chat entry
        user_message: Message sent by the user
        bot_response: Response generated by the bot
        timestamp: Time when the message was created
    """
    
    __tablename__ = "chats"

    id = Column(Integer, primary_key=True, index=True)
    user_message = Column(String)
    bot_response = Column(String)
    timestamp = Column(DateTime, default=datetime.utcnow)